### ISSUE TITLE
Doesn't work with v4

### ISSUE THREAD

**Issue by olafthiele** [jovotech/jovo-starter-web-standalone#7]
Looks like this is meant for v3 of Jovo, but can it be run with v4 or should I run both in parallel?

**Comment by olafthiele** [comment]
@m-ripper would be great to get that running with v4 or is that a bigger refactoring?

**Comment by m-ripper** [comment]
Thanks for pointing out!

There were some changes left in the v4 branch that I just merged. Now the README should be correct.

If there are any more issues, just let me know.

**Comment by olafthiele** [comment]
Yes, my bad, didn't read about the clone option. Works now. Thanks
